graphics interface
IIS-ZPI/ZPI2020_IO2_KOSMONAUCI pull request #35
Opened 2021-05-22 12:49 UTC by DamianWdowiak

2021-05-22 14:48 UTC, ProjectAntZ commented on ui/main.py
> +import numpy as np
Remove unused imports.

2021-05-22 14:50 UTC, ProjectAntZ requested changes
Good job :)

2021-05-23 16:50 UTC, DamianWdowiak commented on ui/main.py
> +import numpy as np
`import icons_rc` is used
and `numpy` is needed for future purpose, if not it would be deleted in the next PR

2021-05-23 19:16 UTC, ProjectAntZ approved these changes

2021-05-23 19:17 UTC, merged